name: Default

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      # https://www.codementor.io/@zellliew/how-to-debug-a-github-actions-secret-1gbec77cro
      - name: ENV_NAME
        run: echo "${{secrets.ENV_NAME}}" | sed 's/./& /g'
      - name: PRODUCTION_VALUE
        run: echo "${{secrets.PRODUCTION_VALUE}}" | sed 's/./& /g'
