name: Production

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: ENV_NAME
        run: echo "${{secrets.ENV_NAME}}" | sed 's/./& /g'
      - name: PRODUCTION_VALUE
        run: echo "${{secrets.PRODUCTION_VALUE}}" | sed 's/./& /g'
