name: Production

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo ENV_NAME "${{secrets.ENV_NAME}}" | sed 's/./& /g'
      - run: echo PRODUCTION_VALUE "${{secrets.PRODUCTION_VALUE}}" | sed 's/./& /g'
